export enum StoreLocations {
  RELATIVE_WINDOW = 'relative',
  STANDINGS_WINDOW = 'standings',
  INPUT_GRAPH_WINDOW = 'inputGraph',
  INPUTS_WINDOW = 'inputs',
  FUEL_CALCULATOR = 'fuelCalculator',
  TRACK_MAP = 'trackMap',
  TEST_OVERLAY = 'testOverlay',
  // Individual Advanced Panel Overlays
  SPEED_OVERLAY = 'speedOverlay',
  RPM_OVERLAY = 'rpmOverlay',
  RPM_LIGHTS_OVERLAY = 'rpmLightsOverlay',
  GEAR_OVERLAY = 'gearOverlay',
  ABS_OVERLAY = 'absOverlay',
  TIRE_TEMP_OVERLAY = 'tireTempOverlay',
  TIRE_WEAR_OVERLAY = 'tireWearOverlay',
  TIRE_SLIP_OVERLAY = 'tireSlipOverlay',
  SETTINGS = 'settings',
  MAIN = 'Race Vision',
}
